name: Bug Report
description: File a bug report
title: '[Bug]: '
labels: ['bug']
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to fill out this bug report!
    - type: textarea
      id: description
      attributes:
          label: Describe the Bug
          description: A clear and concise description of what the bug is.
          placeholder: Tell us what happened...
      validations:
          required: true
    - type: textarea
      id: reproduce
      attributes:
          label: Steps to Reproduce
          description: Steps to reproduce the behavior
          placeholder: |
              1. Go to '...'
              2. Click on '....'
              3. Scroll down to '....'
              4. See error
      validations:
          required: true
    - type: textarea
      id: expected
      attributes:
          label: Expected Behavior
          description: A clear and concise description of what you expected to happen.
      validations:
          required: true
    - type: textarea
      id: actual
      attributes:
          label: Actual Behavior
          description: What actually happened, including any error messages or logs.
      validations:
          required: true
    - type: textarea
      id: screenshots
      attributes:
          label: Screenshots
          description: If applicable, add screenshots to help explain your problem.
          placeholder: Add screenshot URLs here...
    - type: textarea
      id: environment
      attributes:
          label: Environment
          description: Please complete the following information
          value: |
              - OS: [e.g. Windows 10, macOS 12.0, Ubuntu 20.04]
              - Node Version: [e.g. 18.12.0]
              - pnpm Version: [e.g. 8.5.0]
              - MongoDB Version: [e.g. 6.0]
              - Browser: [e.g. Chrome 115, Firefox 116]
      validations:
          required: true
    - type: textarea
      id: context
      attributes:
          label: Additional Context
          description: Add any other context about the problem here.
